### ISSUE TITLE
mail interface

### ISSUE THREAD

**Issue by rcrath** [digiah/memberconnect#27]
Logged in users should be able to filter a list of members and send an email to the the members in returned results.  Requires #15 (eventually) and #16 (immediately).

**Comment by Viltaria** [comment]
CC the authenticated user

**Comment by Viltaria** [comment]
Post Launch feature

**Comment by rcrath** [comment]
@Viltaria are saying the whole feature is post launch, or just the cc part?  This is a pretty important feature so if at all possible would like to include it.

**Comment by rcrath** [comment]
@Viltaria fixed trailing slashes
