### ISSUE TITLE
Separate Login

### ISSUE THREAD

**Issue by Viltaria** [digiah/memberconnect#32]
Issues surrounding the ADMIN and user LOGIN functionality

**Comment by damg70** [comment]
Login for ADMIN works

Editing users seems to work.

BUT there are some issues with how the interface and navigation works going forward.

If i start [here](https://dahi.manoa.hawaii.edu/njs/)

<img width="1057" alt="mc-nav-menu" src="https://user-images.githubusercontent.com/6117953/30228539-fd92a654-9479-11e7-9e98-2bfea4e0025f.png">

The page navigation appears before login.

But if i log in:

**The page navigation disappears**

<img width="1060" alt="mc-nav-no-menu-admin" src="https://user-images.githubusercontent.com/6117953/30228566-13c9b67e-947a-11e7-89d2-04a6b2b8bd9a.png">

SEARCH from this point works...

<img width="1162" alt="mc-menu-search" src="https://user-images.githubusercontent.com/6117953/30228637-447f2a60-947a-11e7-91f8-ef57e96dfab6.png">

... and i can edit stuff nicely.

BUT 

1. Clicking the X in the search menu **does not** reset the cards on the screen
2. Deleting the text in the search menu **does** reset the cards on the screen.

Search seems to continue to work nicely despite the two issues above. However, @damg70 encountered a bug where he couldn't find his own entry and had to go back to the main screen and log in as admin again to "reset" the database.
