### ISSUE TITLE
UH LOGIN PROBLEMS

### ISSUE THREAD

**Issue by damg70** [digiah/memberconnect#33]
@rcrath @Viltaria 
Tyler showed me how one of the two URLs that we requested to have access to the UH ID login system has been approved.

[https://dahi.manoa.hawaii.edu/njs/admin](https://dahi.manoa.hawaii.edu/njs/admin) has been approved

but apparently

[https://dahi.manoa.hawaii.edu/njs/](https://dahi.manoa.hawaii.edu/njs/) has not.

we get the "this application is not authorized to use CAS" message.

According to UH policy @rcrath is the only person authorized to contact them to have them correct this problem. Seeing as there is no real difference between the njs and the admin landing pages this is probably a bureaucratic error on their part.

**Comment by rcrath** [comment]
made application for njs
