### ISSUE TITLE
Memberconnect Card Interface

### ISSUE THREAD

**Issue by damg70** [digiah/memberconnect#35]
This issue focuses on UI issues with MC cards.

**BROWSE MODE** 

_No one is logged in._

1. We need to finalize which fields from the MCdb are visible in "card mode" and which ones will be revealed via clicks on UI elements.

Are we going to go to a "full page" version of the member by clicking on an icon in the card? Or are we going to have more icons like the up-arrow that reveal other details? 

@damg70 imagines that the more-used the system becomes, the more we will need "home pages" instead of relying exclusively on the cards as the interface.

**ADMIN MODE**

_Admin is logged in._

1. When you click the pencil to edit, we need _labels_ on the fields.

2. We need to decide whether one can edit the entire record from this card view or the admin is taken to a "master" editing page.

3. As it stands, it may be a bad idea to be able to simultaneously edit various users... what happens if you click the "back" button in the middle of edits? The pop-up windows get user attention in a very strong way... maybe we simply need to warn the admin that they are moving to a different record if they start clicking on other cards.

4. If you're logged in, you therefore are a kind of super-user, no? The general UI should act the same as it does for MEMBER MODE (see below).

**MEMBER MODE**

_Member is logged in._

1. Is the logged in user taken straight to their "master" page for editing and updating?

2. Claimed and edited Achievements should be clearly visible here...

3. Or, once you're logged in, perhaps there should there be a little dashboard above the cards that indicates stuff like point 2?

**Comment by Viltaria** [comment]
Labels are in progress

**Comment by damg70** [comment]
## Candidates for Fields:

**First, Last, Email, Affiliation, Role, Interests, Website, Achievement**

First, Last, Email, Affiliation - varchar

## Role - drop-down

Undergraduate, Graduate, Admin, Faculty, Staff, Community, Other

## Interests - tab-based selection

**Comment by Viltaria** [comment]
Moving user editing, creation, deletion to a standalone page

**Comment by rcrath** [comment]
for interests, data structure, see #37, For achievemnts see #36.

**Comment by rcrath** [comment]
re:

>We need to finalize which fields from the MCdb are visible in "card mode" and which ones will be revealed via clicks on UI elements.

@damg70, we have tacit permission only to publish the fields currently in the public facing-part of the google spreadsheet (i.e., what actually appears on the web site) to the public/not-logged-in MCdb viewer.  Because every member has access to the google spreadsheet, we have permission for members who are actively logged in to MCdb to see the rest of the fields, with email address being the most important. We could also let logged in members email each other through the interface without actually showing their email addresses at all, which might be better.

**Comment by rcrath** [comment]
it looks like email is the only one that is limited to logged in users.

**Comment by rcrath** [comment]
Se #20 and #18
