### ISSUE TITLE
logout function

### ISSUE THREAD

**Issue by rcrath** [digiah/memberconnect#42]
need to be able to logout of admin and user dbases from any ui page.

**Comment by damg70** [comment]
the logout link from the main web login page goes here: https://aruba-master.its.hawaii.edu/cgi-bin/login?cmd=logout 

the logout link from the library link to oxford english dictionary goes here: http://www.oed.com.eres.library.manoa.hawaii.edu/LOGOUT

the logout link from the library itself is elaborate and equally customized... 

but i think if we go with the first one from links on a given memberconnect page we should be good... then again, that would log them out ENTIRELY... it's unclear how the cookies between the different sites that use UH authorization work together or against each other. there may also be a generic link in the documentation for working with these features.

**Comment by rcrath** [comment]
It is ok to log  out.  As you would guess, it is not uniform.  It depends on the service you want to access whether you need to log in again.  Pretty sure all logging out does is scratch the cookie.  

I can't see the aruba one. Aruba is the wireless service.  I don't think we want to disconnect people's wireless.  that would be a pain.  THe OED link does not connect through UH it seems.  [Here is a page](http://www2.hawaii.edu/~rrath/secondary.html) full of library services that need to be logged in to with links to them through the library interface. Maybe that would provide a good example?

**Comment by damg70** [comment]
i’m wondering if there isn’t a simple url that they point us to based on having logged in via the web… perhaps as you track down the bug they keep throwing at us you could toss that on the “trouble ticket” as well? i’ll look in to that page though.

**Comment by rcrath** [comment]
@damg70 have you looked through the [cas help for logout](https://www.hawaii.edu/bwiki/display/UHIAM/CAS+Developer+Documentation#CASDeveloperDocumentation-logout)?  It looks straight forward from there, just need to delete the cookie to logout of single session login.

**Comment by damg70** [comment]
what we are looking for is here:

https://www.hawaii.edu/bwiki/display/UHIAM/CAS+Developer+Documentation#CASDeveloperDocumentation-logout

it's a straightforward URL that clears the CAS session variables.

> To logout a user and prevent her from automatically logging back into a Web application, the Web application can forward the user to the Logout URL of UH Login. That URL will destroy the ticket-granting cookie that enables the single sign-on feature and gives the user a page that informs them that they have logged out of UH Login.
> 
> https://$WEBLOGIN-HOST/cas/logout
> 
> To logout a user and prevent her from automatically logging back into a Web application, the Web application can forward the user to the Logout URL of UH Login. That URL will destroy the ticket-granting cookie that enables the single sign-on feature and redirect the user to the URL identified by the service parameter.
> 
> https://$WEBLOGIN-HOST/cas/logout?service=https://myserver/myapp

So this is a matter of making the onclick of a button or the href of a link go to either of those URLs.

**Comment by rcrath** [comment]
@Viltaria this seems ready to implement. ^^
